webtalk_init -webtalk_dir /home/sam/FS/FS_LAB1_VIVADO/comparator/comparator.sim/sim_1/behav/xsim/xsim.dir/test_comp_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar 26 15:59:57 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4a9b2e29-21a3-4e1a-97b3-4b33bfa93508" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8e13773747074c3f8030acb3fd22a9a6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Zorin" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Zorin OS 17" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800.551 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115120_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3587651771 -regid "" -xml /home/sam/FS/FS_LAB1_VIVADO/comparator/comparator.sim/sim_1/behav/xsim/xsim.dir/test_comp_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/sam/FS/FS_LAB1_VIVADO/comparator/comparator.sim/sim_1/behav/xsim/xsim.dir/test_comp_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/sam/FS/FS_LAB1_VIVADO/comparator/comparator.sim/sim_1/behav/xsim/xsim.dir/test_comp_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
